# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Zijin Zhang
tagline:          #'A Jekyll theme'
description:      'Assistant Professor' 
url:              //www.zijinzhang.com
baseurl:          //www.zijinzhang.com

# author:
#   name:           'Mark Otto'
#   url:            https://twitter.com/mdo

#paginate:         5
gems:                [jekyll-paginate]
paginate:            6
paginate_path:       "page:num"

# Custom vars
#version:          #2.1.0

github:
  repo:           //github.com/zijinzhang123/zijinzhang123.github.io

plugins:
  - jekyll-gist